---
# yamllint disable rule:line-length
name: Code Coverage Report Action
author: Inisghts Engineering
description: Action that converts a Cobertura XML report into a markdown report.

inputs:
  path:
    description: Path to the Cobertura coverage XML report.
    required: false
    default: "."
  threshold:
    description: The minimum allowed coverage percentage, as a real number.
    required: false
    default: 0
  fail:
    description: Fail the action when the minimum coverage was not met.
    required: false
    default: true
  publish:
    description: Publish the coverage report as an issue comment.
    required: false
    default: false
  diff:
    description: Create a diff of the coverage report.
    required: false
    default: false
  diff-branch:
    description: Branch to diff against.
    required: false
    default: main
  diff-storage:
    description: Branch where coverage reports are stored for diff purposes.
    required: false
    default: _xml_coverage_reports

branding: # https://feathericons.com/
  icon: "umbrella"
  color: "red"

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install pycobertura
      uses: BSFishy/pip-action@v1
      with:
        packages: pycobertura==2.1.0

    - name: Generate text report
      run: |
        pycobertura show ${{ inputs.path }} --output .coverage-output
        cat .coverage-output
      shell: bash

    - name: Get branch names
      id: branch-names
      uses: tj-actions/branch-names@v5.1

    - name: Fetch report from ${{ inputs.diff-storage }}
      if: "contains(inputs.diff, 'true')"
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.diff-storage }}
        path: ${{ inputs.diff-storage }}

    - name: Generate diff against ${{ inputs.diff-branch }}
      if: "contains(inputs.publish, 'true')"
      run: |
        if [ -f "${{ inputs.diff-storage }}/${{ inputs.path }}" ]
        then {
          pycobertura diff --no-color --no-source ${{ inputs.path }} \
            ${{ inputs.diff-storage }}/${{ inputs.path }} \
            --output .coverage-output.diff
          cat .coverage-output.diff
        } else {
          echo "${{ inputs.diff-storage }}/${{ inputs.path }} not found! Not diffing."
        }
        fi
      shell: bash

    - name: Get total
      run: |
        grep -E "^TOTAL " .coverage-output | \
          awk '{print $NF}' | tr -d '%' > .coverage-total
      shell: bash

    - name: Generate issue comment body
      if: "contains(inputs.publish, 'true')"
      run: |
        echo -e "## Code Coverage Summary\n" > .coverage-output.final
        echo -e "\`\`\`" >> .coverage-output.final
        cat .coverage-output >> .coverage-output.final
        echo -e "\n\`\`\`\n" >> .coverage-output.final
        if [[ "${{ inputs.diff }}" == "true" && -f .coverage-output.diff ]]
        then {
          echo -e "### Diff against ${{ inputs.diff-branch }}\n" > .coverage-output.final
          echo -e "\`\`\`" >> .coverage-output.final
          cat .coverage-output.diff >> .coverage-output.final
          echo -e "\n\`\`\`\n" >> .coverage-output.final
        }
        fi
        echo -e "\nResults for commit: ${{ github.sha }}\n" >> .coverage-output.final
        echo -e "\n_Minimum allowed coverage is \`${{ inputs.threshold }}%\`_\n" >> .coverage-output.final
        echo -e "\n:recycle: This comment has been updated with latest results\n" >> .coverage-output.final
      shell: bash

    - name: Post as comment
      if: "contains(inputs.publish, 'true')"
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: ${{ inputs.path }}
        path: .coverage-output.final
        GITHUB_TOKEN: ${{ github.token }}

    - name: Check threshold
      if: "contains(inputs.fail, 'true')"
      run: |
        with open('.coverage-total', 'r') as t:
          total = float(t.read().rstrip())
        min = float('${{ inputs.threshold }}')
        if total < min:
          raise SystemExit(
            f"Total Coverage of {total}% falls below minimum threshold of {min}%."
          )
      shell: python

    - name: Clean up intermediate files
      if: always()
      run: rm -f .coverage-output.final .coverage-output .coverage-total .coverage-output.diff
      shell: bash

    - name: Push XML report to ${{ inputs.diff-branch }}
      if: ${{ inputs.diff && (steps.branch-name.outputs.current_branch == inputs.diff-branch) }}
      uses: EndBug/add-and-commit@v7
      with:
        remove: 'rm -rf *'
        add: "${{ inputs.path }}"
        branch: some-branch
        message: 'Your commit message'
        push: true
        default_author: github_actions
        committer_name: GitHub Actions
        committer_email: actions@github.com
